name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.0.11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: 11.0.11
    - name: Install sbt
      run: |
       sudo apt-get update 
       sudo apt-get install -y gnupg2 curl
       echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
       curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
       sudo apt-get update 
       sudo apt-get install -y sbt
    - name: Run tests
      run: |
       export SBT_OPTS="-Xmx3G -XX:+UseG1GC -Xss2M" && sbt test
